# Setup
title:               iyusufali
# tagline:             'A blog'
# description:         'A blog'
url:                 http://iyusufali.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ibrahim Yusufali
  url:               https://twitter.com/ityusufali
  email:             ga4dw21gc@mozmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
